# Default configuration for shilads-helpers

app:
  name: shilads-helpers
  version: 1.0.0
  author: Shilad Sen

# Logging configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# Path configurations
paths:
  # Add common paths used by your scripts
  data_dir: ~/data
  output_dir: ~/output

# Common tool settings
tools:
  # Add tool-specific settings as needed
  max_threads: 4
  timeout: 300  # seconds

openai:
  organization: "override-in-local-yaml"
  api_key: "override-in-local-yaml"
  model: gpt-5
  pydantic_ai_settings:
    openai_reasoning_effort: low


# Directory anonymizer settings
anonymizer:
  # File types to process (by extension)
  file_types:
    - .py
    - .txt
    - .md
    - .qmd
    - .rmd
    - .yaml
    - .yml
    - .json
    - .csv
    - .log
    - .sh
    - .bash
    - .zsh
    - .js
    - .ts
    - .jsx
    - .tsx
    - .css
    - .xml
    - .conf
    - .cfg
    - .ini
    - .env
    - .sql
    - .r
    - .R
    - .ipynb
    
  # Patterns to exclude from processing
  exclude_patterns:
    - .git
    - .venv
    - venv
    - env
    - __pycache__
    - node_modules
    - .DS_Store
    - "*.pyc"
    - "*.pyo"
    - "*.pyd"
    - "*.so"
    - "*.dll"
    - "*.dylib"
    - "*.exe"
    - "*.bin"
    - "*.zip"
    - "*.tar"
    - "*.gz"
    - "*.rar"
    - "*.7z"
    - "*.jpg"
    - "*.jpeg"
    - "*.png"
    - "*.gif"
    - "*.bmp"
    - "*.ico"
    - "*.svg"
    - "*.pdf"
    - "*.doc"
    - "*.docx"
    - "*.xls"
    - "*.xlsx"
    - "*.ppt"
    - "*.pptx"
    
  # Output settings
  output:
    # Directory for anonymized output (relative to current dir)
    output_dir: anonymized_output
    # Where to save the mapping file
    mapping_file: anonymization_mapping.json
    
  # Anonymization options
  options:
    # Whether to anonymize file and directory names
    anonymize_filenames: true
    # Whether to preserve directory structure
    preserve_structure: true
    # Whether to create a summary report
    create_report: true
    
  # Custom patterns (regex) and their replacements
  custom_patterns: {}
  
  # Presidio PII detection configuration
  local_model:
    # Chunking configuration
    max_input_tokens: 1000  # Maximum tokens per chunk

    # Presidio backend configuration
    presidio:
      # Analyzer settings
      language: "en"  # Language code for analysis
      confidence_threshold: 0.3  # Minimum confidence score (0.0-1.0)

      # NLP Engine Provider configuration (passed directly to NlpEngineProvider)
      nlp_configuration:
        nlp_engine_name: "spacy"  # NLP engine to use
        models:
          - lang_code: "en"
            model_name: "en_core_web_lg"
        ner_model_configuration:
          labels_to_ignore:
            - O
            - MONEY
            - ORG
            - GPE
            - NORP
            - DATE
            - TIME
            - PERCENT
            - QUANTITY
            - CARDINAL
            - ORDINAL
            - LAW
            - EVENT
            - PRODUCT
            - WORK_OF_ART
            - FAC
            - LANGUAGE